-- Presence / geolocation fields for the admin live map (all nullable, additive)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastActiveAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastActivity" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastPath" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastCity" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastRegion" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastCountry" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLat" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLng" DOUBLE PRECISION;
