/**
 * POST /api/meme-lab/to-drive
 *
 * Content Lab -> Google Drive. Saves generated Meme Lab content into a Drive
 * folder the user chose. STORAGE ONLY: this route never schedules and never
 * publishes. Storage intent and publishing intent are separate concepts, and
 * this is the storage half.
 *
 * It reuses the existing Drive layer wholesale — same session convention as
 * /api/google/files, same getDriveAccessToken() token resolver (which refreshes
 * from the stored Account row), same full drive scope that moveDriveFile()
 * already relies on. No OAuth logic is duplicated here and no Google
 * credential ever reaches the browser.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { getDriveAccessToken, uploadDriveFile } from '@/app/lib/google/drive';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 60;

const MAX_FILES = 12;
const MAX_FILE_BYTES = 8 * 1024 * 1024;
const MAX_TOTAL_BYTES = 4 * 1024 * 1024;
const ALLOWED_MIME = 'image/jpeg';
const FOLDER_ID = /^(root|[A-Za-z0-9_-]{6,128})$/;

/** Drive caps an appProperties value at 124 bytes. Clip on a byte boundary. */
function clipBytes(value: string, max = 120): string {
  const enc = new TextEncoder();
  if (enc.encode(value).length <= max) return value;
  let out = value;
  while (out.length > 0 && enc.encode(out).length > max) {
    out = out.slice(0, -1);
  }
  return out;
}

/** Only expected Meme Lab content, and never a path. */
function safeFilename(name: string): string {
  const base = (name || 'meme.jpg')
    .replace(/[\\/]/g, '-')
    .replace(/[^A-Za-z0-9._-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^[.-]+/, '')
    .slice(0, 120);
  const stem = base.replace(/\.[A-Za-z0-9]+$/, '') || 'meme';
  return `${stem}.jpg`;
}

function toAppProperties(raw: unknown): Record<string, string> {
  if (!raw || typeof raw !== 'object') return {};
  const meta = raw as Record<string, unknown>;
  const keys = [
    'contentId', 'subject', 'topText', 'bottomText', 'caption',
    'template', 'mode', 'source', 'createdAt', 'rightsStatus',
  ];
  const out: Record<string, string> = {};
  for (const k of keys) {
    const v = meta[k];
    if (typeof v === 'string' && v) out[`sx_${k}`] = clipBytes(v);
  }
  out.sx_storageProvider = 'google-drive';
  return out;
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.email) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  const user = await prisma.user.findUnique({
    where: { email: session.user.email },
    select: { id: true },
  });
  if (!user) return NextResponse.json({ error: 'User not found' }, { status: 404 });

  let form: FormData;
  try {
    form = await req.formData();
  } catch {
    return NextResponse.json({ error: 'Expected multipart/form-data' }, { status: 400 });
  }

  const provider = String(form.get('provider') || 'google-drive');
  if (provider !== 'google-drive') {
    return NextResponse.json(
      { error: `Unsupported storage provider: ${provider}` },
      { status: 400 }
    );
  }

  const folderId = String(form.get('folderId') || '').trim();
  if (!FOLDER_ID.test(folderId)) {
    return NextResponse.json({ error: 'A valid destination folder is required' }, { status: 400 });
  }

  const files = form.getAll('files').filter((f): f is File => f instanceof File);
  const metas = form.getAll('meta').map(m => String(m));

  if (files.length === 0) {
    return NextResponse.json({ error: 'No files provided' }, { status: 400 });
  }
  if (files.length > MAX_FILES) {
    return NextResponse.json(
      { error: `Too many files in one request (max ${MAX_FILES})` },
      { status: 400 }
    );
  }

  let totalBytes = 0;
  for (const f of files) {
    if (f.type !== ALLOWED_MIME) {
      return NextResponse.json(
        { error: 'Only JPEG content generated by the Content Lab can be saved' },
        { status: 400 }
      );
    }
    if (f.size > MAX_FILE_BYTES) {
      return NextResponse.json({ error: `"${f.name}" is too large` }, { status: 400 });
    }
    totalBytes += f.size;
  }
  if (totalBytes > MAX_TOTAL_BYTES) {
    return NextResponse.json(
      { error: 'Batch too large — save fewer items at a time' },
      { status: 400 }
    );
  }

  let token: string;
  try {
    token = await getDriveAccessToken(user.id);
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Google Drive not connected';
    const notConnected = /not connected/i.test(message);
    return NextResponse.json(
      { error: message, driveConnected: !notConnected },
      { status: notConnected ? 403 : 500 }
    );
  }

  const results: Array<{
    filename: string;
    ok: boolean;
    storageFileId?: string;
    webViewLink?: string;
    error?: string;
  }> = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i] as File;
    const filename = safeFilename(file.name);
    try {
      let meta: unknown = {};
      try {
        meta = metas[i] ? JSON.parse(metas[i] as string) : {};
      } catch {
        meta = {};
      }

      const data = Buffer.from(await file.arrayBuffer());
      const uploaded = await uploadDriveFile(token, {
        folderId,
        name: filename,
        mimeType: ALLOWED_MIME,
        data,
        appProperties: toAppProperties(meta),
      });

      results.push({
        filename,
        ok: true,
        storageFileId: uploaded.id,
        webViewLink: uploaded.webViewLink,
      });
    } catch (e) {
      results.push({
        filename,
        ok: false,
        error: e instanceof Error ? e.message : 'Upload failed',
      });
    }
  }

  return NextResponse.json({
    provider: 'google-drive',
    folderId,
    saved: results.filter(r => r.ok).length,
    failed: results.filter(r => !r.ok).length,
    results,
  });
}
