/**
 * Canvas compositor — the browser equivalent of the desktop app's Pillow layer.
 *
 * Text is never generated by a model, it is burned on here: instant, no memory
 * pressure, and it can actually spell. Template images are loaded through our
 * own /api/meme-lab/image proxy so the canvas stays same-origin and
 * toBlob() is not blocked by tainting.
 */

const MEME_FONT_STACK =
  'Impact, "Anton", "Arial Narrow Bold", "Haettenschweiler", "Arial Bold", sans-serif';

export interface RenderOptions {
  templateUrl: string;
  top: string;
  bottom: string;
  fry?: number;      // 0..1
  maxWidth?: number; // px
}

export interface RenderResult {
  blob: Blob;
  objectUrl: string;
  width: number;
  height: number;
}

const imageCache = new Map<string, HTMLImageElement>();

function loadImage(url: string): Promise<HTMLImageElement> {
  const cached = imageCache.get(url);
  if (cached && cached.complete && cached.naturalWidth > 0) {
    return Promise.resolve(cached);
  }
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      imageCache.set(url, img);
      resolve(img);
    };
    img.onerror = () => reject(new Error(`Could not load template: ${url}`));
    img.src = url;
  });
}

/** Greedy word wrap against a measured max width. */
function wrap(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const lines: string[] = [];
  let line = words[0] as string;
  for (let i = 1; i < words.length; i++) {
    const word = words[i] as string;
    const test = `${line} ${word}`;
    if (ctx.measureText(test).width <= maxWidth) {
      line = test;
    } else {
      lines.push(line);
      line = word;
    }
  }
  lines.push(line);
  return lines;
}

/** Shrink the font until the wrapped block fits its box. */
function fitBlock(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
  maxHeight: number,
  startSize: number,
  minSize = 13,
): { size: number; lines: string[] } {
  let size = startSize;
  while (size >= minSize) {
    ctx.font = `${size}px ${MEME_FONT_STACK}`;
    const lines = wrap(ctx, text, maxWidth);
    const lineHeight = size * 1.12;
    const widest = lines.reduce((m, l) => Math.max(m, ctx.measureText(l).width), 0);
    if (widest <= maxWidth && lines.length * lineHeight <= maxHeight) {
      return { size, lines };
    }
    size -= 2;
  }
  ctx.font = `${minSize}px ${MEME_FONT_STACK}`;
  return { size: minSize, lines: wrap(ctx, text, maxWidth) };
}

function drawBlock(
  ctx: CanvasRenderingContext2D,
  text: string,
  position: 'top' | 'bottom',
  W: number,
  H: number,
): void {
  if (!text) return;
  const margin = Math.round(W * 0.04);
  const maxWidth = W - margin * 2;
  const maxHeight = Math.round(H * 0.34);
  const startSize = Math.max(Math.round(H * 0.13), 18);

  const { size, lines } = fitBlock(
    ctx, text.toUpperCase(), maxWidth, maxHeight, startSize,
  );
  const lineHeight = size * 1.12;
  const blockHeight = lines.length * lineHeight;

  ctx.font = `${size}px ${MEME_FONT_STACK}`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'alphabetic';
  ctx.lineJoin = 'round';
  ctx.miterLimit = 2;
  ctx.lineWidth = Math.max(2, size / 6);
  ctx.strokeStyle = '#000000';
  ctx.fillStyle = '#ffffff';

  const firstBaseline =
    position === 'top'
      ? margin + size * 0.9
      : H - margin - blockHeight + size * 0.9;

  lines.forEach((line, i) => {
    const y = firstBaseline + i * lineHeight;
    ctx.strokeText(line, W / 2, y);
    ctx.fillText(line, W / 2, y);
  });
}

/**
 * The decay pass. Oversaturate, crush contrast toward blown yellows and reds,
 * then re-encode hard as JPEG so compression artifacts show.
 */
async function deepFry(
  source: HTMLCanvasElement,
  intensity: number,
): Promise<HTMLCanvasElement> {
  const out = document.createElement('canvas');
  out.width = source.width;
  out.height = source.height;
  const ctx = out.getContext('2d');
  if (!ctx) return source;

  ctx.filter =
    `saturate(${1 + 2.2 * intensity}) ` +
    `contrast(${1 + 1.0 * intensity}) ` +
    `brightness(${1 + 0.12 * intensity})`;
  ctx.drawImage(source, 0, 0);
  ctx.filter = 'none';

  // warm shift toward the classic blown-out orange
  ctx.globalCompositeOperation = 'overlay';
  ctx.fillStyle = `rgba(255, 120, 0, ${0.16 * intensity})`;
  ctx.fillRect(0, 0, out.width, out.height);
  ctx.globalCompositeOperation = 'source-over';

  // round-trip through low-quality JPEG for real compression artifacts
  const quality = Math.max(0.05, 0.32 - 0.24 * intensity);
  const dataUrl = out.toDataURL('image/jpeg', quality);
  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const i = new Image();
    i.onload = () => resolve(i);
    i.onerror = () => reject(new Error('deep fry re-encode failed'));
    i.src = dataUrl;
  });
  ctx.drawImage(img, 0, 0, out.width, out.height);
  return out;
}

function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob(b => {
      if (b) resolve(b);
      else reject(new Error('canvas.toBlob returned null'));
    }, 'image/png');
  });
}

export async function renderMeme(opts: RenderOptions): Promise<RenderResult> {
  const { templateUrl, top, bottom, fry = 0, maxWidth = 900 } = opts;
  const img = await loadImage(templateUrl);

  const scale = img.naturalWidth > maxWidth ? maxWidth / img.naturalWidth : 1;
  const W = Math.round(img.naturalWidth * scale);
  const H = Math.round(img.naturalHeight * scale);

  let canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Canvas 2D context unavailable');

  ctx.drawImage(img, 0, 0, W, H);
  drawBlock(ctx, top, 'top', W, H);
  drawBlock(ctx, bottom, 'bottom', W, H);

  if (fry > 0) canvas = await deepFry(canvas, fry);

  const blob = await canvasToBlob(canvas);
  return {
    blob,
    objectUrl: URL.createObjectURL(blob),
    width: W,
    height: H,
  };
}
